# Generated by Django 4.2.7 on 2025-01-05 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='hospital',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=datetime.datetime(2025, 1, 5, 7, 28, 57, 506328, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
